config/routes.rb
WinAGift::Application.routes.draw do

  match '/choose', :to => 'games#choose'
  match '/play',   :to => 'games#play'
  match '/win',    :to => 'games#win'
  match '/share',  :to => 'games#share'
  root :to => 'games#choose'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def choose
  	@title = "Choose"

    if cookies[:alias].nil?
      new_alias = [('a'..'z').to_a.shuffle.first, 
        [('a'..'z').to_a.shuffle[0..3], 
          (0..9).to_a.shuffle[0..1]].shuffle].join
      @welcome = "Hello new user. Your alias will be " + new_alias
      cookies[:alias] = new_alias
    else
      @welcome = "Hi, " + cookies[:alias] + ". Good to see you again."
    end
  end

  def play
  	@title = "Play"
  end

  def win
  	@title = "Win"
  end

  def share
  	@title = "Share"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def logo
		image_tag("logo_gift_s.png", :alt => "SeeNWin", :class => "round")
	end

	def title
		base_title ="Win A Gift"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/choose.html.erb
<div class="in_center">
	<h1>Choose</h1>
</div>
<section class="round">
	<p><%= @welcome %></p>
	<%= link_to image_tag("choose2.png", :alt => "Play", :class => "in_center round"), play_path %>
	<p>What gift do you like to play for?</p>
</section>

app/views/games/play.html.erb
<div class="in_center">
	<h1>Play</h1>
</div>
<section class="round">
	<%= image_tag("view1.png", :alt => "View", :class => "in_center round") %>
	<p>After the video will end, check your luck...</p>
	<nav class="button">
		<%= link_to "you Win", win_path %>
	</nav>
</section>

app/views/games/share.html.erb
<div class="in_center">
	<h1>Share</h1>
</div>
<section class="round">
	<%= image_tag("share.png", :alt => "Share", :class => "in_center round") %>
	<p>Please share this game with your friends.</p>
	<nav class="button">
		<%= link_to "try again", choose_path %>
	</nav>
</section>

app/views/games/win.html.erb
<div class="in_center">
	<h1>Winner</h1>
</div>
<section class="round">
	<%= image_tag("win.png", :alt => "Winner", :class => "in_center round") %>
	<p>Contact the firm to recieve your prize.</p>
	<nav class="button">
		<%= link_to "Share", share_path %>
	</nav>
</section>

app/views/layouts/_footer.html.erb
<footer>

</footer>

app/views/layouts/_header.html.erb
<header>
	<%= logo %>
</header>

app/views/layouts/_stylesheets.html.erb
	<!--[if lt IE 9]>
	<script src=""http://html5shiv.googlecode.com/svn/trunk/html5.js""></script>
	<![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	<title><%= title %></title>
 	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
</head>
<body>
  <div class="container">
	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
  </div>
</body>
</html>